name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Copy report directories
        run: |
          cd reports
          for dir in */; do
            dirname=${dir%/}
            mkdir -p ../dist/$dirname
            cp -r $dirname/dist/* ../dist/$dirname/
          done
          echo '<!DOCTYPE html><html><head><title>Reports</title></head><body>' > ../dist/index.html
          echo '<h1>Available Reports</h1><ul>' >> ../dist/index.html
          for dir in */; do
            dirname=${dir%/}
            echo "<li><a href='./$dirname/'>$dirname</a></li>" >> ../dist/index.html
          done
          echo '</ul></body></html>' >> ../dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
