name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Copy report directories
        run: |
          mkdir -p dist
          cp CNAME dist/
          cp templates/index.html dist/

          cd reports
          for dir in */; do
            dirname=${dir%/}
            mkdir -p ../dist/$dirname
            cp -r $dirname/dist/* ../dist/$dirname/


            formatted_name=$(echo $dirname | tr '-' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1')
            card_html="<div class=\"report-card\"><a href=\"./$dirname/\"><h2 class=\"report-title\">$formatted_name</h2></a></div>"


            sed -i.bak "s|<div class=\"reports-grid\" id=\"reports-list\">|<div class=\"reports-grid\" id=\"reports-list\">\n        $card_html|" ../dist/index.html
          done

          find ../dist -name "*.bak" -type f -delete

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
